/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author MZULETA4
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    double v[];

    public Principal() {
        initComponents();
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdMostrar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtL = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoManual = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdLlenadoAutomatico = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Operaciones Con Vectores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos iniciales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Longitud");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLKeyTyped(evt);
            }
        });
        jPanel2.add(txtL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        cmdLlenadoManual.setText("Llenado Manual");
        cmdLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 30));

        cmdLlenadoAutomatico.setText("Llenado Automatico");
        cmdLlenadoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, 270));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 100));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        setSize(new java.awt.Dimension(531, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed

        int longitud;

        if (txtL.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite La Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtL.requestFocusInWindow();
        } else if (txtL.getText().trim().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "Digite Una Longitud Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtL.requestFocusInWindow();
            txtL.selectAll();
        } else {

            longitud = Integer.parseInt(txtL.getText());
            v = new double[longitud];
            JOptionPane.showMessageDialog(this, "Vector Creado Satisfatoriamente");
            txtL.setText("");
            
        cmdCrear.setEnabled(false);
        cmdLlenadoManual.setEnabled(true);
        cmdLlenadoAutomatico.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(false);

        }
        

    }//GEN-LAST:event_cmdCrearActionPerformed

    private void txtLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLKeyTyped

    private void cmdLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoManualActionPerformed

        double n;
        int aux, res;
        boolean sw = true;
       
        for (int i = 0; i < v.length; i++) {
            do{
            aux = 1;    
            
            try{
            n = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el elemento en la posición: " + i));
              v[i] = n;
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Digite la información correctamente","Error",JOptionPane.ERROR_MESSAGE);
                aux=0;
            }catch (NullPointerException e){
                res = JOptionPane.showConfirmDialog(this, "¿Desea salir?","Salir",JOptionPane.YES_NO_OPTION);
                 if (res == 0) {
                    aux = 1;
                    i = v.length;
                    sw = false;
                } else{
                     aux = 0;
                 }
            }
            }while(aux == 0);
        }
        cmdCrear.setEnabled(false);
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdMostrar.setEnabled(sw);
        cmdBorrar.setEnabled(true);

    }//GEN-LAST:event_cmdLlenadoManualActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        
        for (int i = 0; i < v.length; i++) {
            txtR.append("" + v[i] + "\n");

        }
        
        cmdCrear.setEnabled(false);
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);

        
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed

        txtL.setText("");
        txtR.setText("");
        txtL.requestFocusInWindow();
        v = null;
        
        cmdCrear.setEnabled(true);
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(true);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int longitud;

        if (txtL.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite La Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtL.requestFocusInWindow();
        } else if (txtL.getText().trim().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "Digite Una Longitud Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtL.requestFocusInWindow();
            txtL.selectAll();
        } else {

            longitud = Integer.parseInt(txtL.getText());
            v = new double[longitud];
            JOptionPane.showMessageDialog(this, "Vector Creado Satisfatoriamente");
            txtL.setText("");

        cmdCrear.setEnabled(false);
        cmdLlenadoManual.setEnabled(true);
        cmdLlenadoAutomatico.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(false);

        }
        

        }
    }//GEN-LAST:event_txtLKeyPressed

    private void cmdLlenadoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutomaticoActionPerformed
        
        double n;
        for (int i = 0; i < v.length; i++) {
            n = (int) (Math.random()*25+1);
            v[i] = n;
        }
         
        
        JOptionPane.showMessageDialog(this, "Vector Llenado Satisfactoriamente");
        
        cmdCrear.setEnabled(false);
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdBorrar.setEnabled(true);

    }//GEN-LAST:event_cmdLlenadoAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenadoAutomatico;
    private javax.swing.JButton cmdLlenadoManual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
